using System;
using System.Text;
using IPod;
using NUnit.Framework;

namespace IPod.Tests
{
    [TestFixture]
    public class HashTests
    {
        //private string tarball_path = "ipod-test-db-hashed.tar.gz";

        [SetUp]
        public void SetUp ()
        {
        }

        [TearDown]
        public void TearDown ()
        {
        }

        [Test]
        public void TestHash ()
        {
            byte [] hash = DatabaseHasher.GetHash ("ipod-test-db-hashed.db", "000A27001A26973B");
            StringBuilder sb = new StringBuilder ();
            foreach (byte b in hash) {
                sb.AppendFormat ("{0:x}", b);
            }

            // This hash literal was generated by libgpod
            Assert.AreEqual ("e7d3978a2a9e6bdcb196be1ea6e6595a897f69d4", sb.ToString ());
        }
    }
}
